// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtV4wA6yxAmTwDDru4hfZyM6vrms-eMqo',
    appId: '1:1030969863148:web:dddc1a923a97e06b196ec9',
    messagingSenderId: '1030969863148',
    projectId: 'foodzone-23448',
    authDomain: 'foodzone-23448.firebaseapp.com',
    storageBucket: 'foodzone-23448.appspot.com',
    measurementId: 'G-4WR113FVTD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0mf4IdncpQ03Wf-gNbtenB8MPRok1Dzg',
    appId: '1:1030969863148:android:d591df8b7bedabbc196ec9',
    messagingSenderId: '1030969863148',
    projectId: 'foodzone-23448',
    storageBucket: 'foodzone-23448.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC19K6JV9SYb1JucB0hJYjMR1T0V4rjZK0',
    appId: '1:1030969863148:ios:f907f6581a0aff0a196ec9',
    messagingSenderId: '1030969863148',
    projectId: 'foodzone-23448',
    storageBucket: 'foodzone-23448.appspot.com',
    iosClientId: '1030969863148-m761a6pq8to7mnbgoso4gj76m83obh5q.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFoodzone',
  );
}
